name=input("Enter Your Player Name:")
age=int(input("Enter Your Player`s Age:"))
print(age)
print(name)
favorite_color=input("Enter Your Favorite Color:")
print(favorite_color)
favorite_food=input("Enter Your Favorite Food:")
print(favorite_food)
job=input("Enter Your Job:")
print(job)